version: '3.1'
services:
  webapi:
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - "5000:80"
  webmvc:
    build:
      context: .
      dockerfile: src/WebMVC/Dockerfile
    ports:
      - "5001:80"